title: "Asset Monitoring and Predictive Maintenance"
sponsor: "FPoliSolutions, LLC"

# Assuming the use of custom variables for content structure
content_structure:
  - section: "Project details"
    url: "#Project-details"
  - section: "Computer experiments to study patterns"
    url: "#Computer-experiments-to-study-patterns"
  - section: "Data"
    url: "#Data"
  - section: "Project instructions"
    url: "#Project-instructions"
  - section: "Steps"
    subsections:
      - title: "EDA and Preprocessing"
        url: "#EDA-and-Preprocessing"
      - title: "Cluster Analysis"
        url: "#Cluster-Analysis"
      - title: "Models"
        url: "#Models"
      - title: "Prediction"
        url: "#Prediction"
      - title: "Performance"
        url: "#Performance"
      - title: "Extra"
        extra_sections:
          - title: "SVC"
            url: "#SVC"
          - title: "Neural Net"
            url: "#Neural-Net"
      - title: "Summary"
        url: "#Summary"
      - title: "Things to answer and to be updated next"
        url: "#Things-to-answer-and-to-be-updated-next"

project_summary: >
  Large engineered systems such as nuclear power plants consist of thousands of interconnected components.
  Components eventually wear out over time which may lead to strange anomalies, faults, and system failures.
